### ISSUE TITLE
Error:  Sync Project With Build Files. 

### ISSUE THREAD

**Issue by Jungle666** [dpoluyanov/bazel-wsl#1]
Syncing project: Sync (full)...
Command: git diff --name-status --no-renames 7ece8c0f5b493d87c8d2319b9fe61ac19d91566a

Updating VCS...
Running Bazel info...
Command: "D:\Program Files\bazel\bazel-wsl.exe" info --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no --

/bin/bash: bazel: command not found

Execute Failed On Windows CMD too：
D:\Program Files\bazel>bazel-wsl.exe --version
/bin/bash: bazel: command not found

**Comment by dpoluyanov** [comment]
you should install `bazel` or [https://github.com/bazelbuild/bazelisk](bazelisk) inside in WSL distro e.g. ubuntu via
```
$ wget -O /usr/local/bin/bazel 'https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64'
$ sudo chmod +X /usr/local/bin/bazel
```

and then retry sync again

**Comment by Jungle666** [comment]
Thansk a lot,It really help me.

**Comment by dpoluyanov** [comment]
Could I close it for now?

**Comment by Jungle666** [comment]
OK,Thanks agin.
