### ISSUE TITLE
Stock on Syncing Project for long long long time.

### ISSUE THREAD

**Issue by Jungle666** [dpoluyanov/bazel-wsl#4]
That really make me crazy. half hours pass and nothing happening

![image](https://user-images.githubusercontent.com/9640834/146030628-aa9ac86a-fef8-4a12-b29e-0932a2ab5d84.png)

**Comment by dpoluyanov** [comment]
What are in bazel console window?

**Comment by Jungle666** [comment]
probem resolved after use right configuretion.
