### ISSUE TITLE
Auto-Configuration Error: Cannot find Java binary bin/java 

### ISSUE THREAD

**Issue by Jungle666** [dpoluyanov/bazel-wsl#5]
ERROR: /home/jungleliu/.cache/bazel/_bazel_jungleliu/748f7d17089974aa1a9125aeba4ea413/external/local_jdk/BUILD.bazel:3:10: in fail_rule rule @local_jdk//:jdk: 
Traceback (most recent call last):
	File "/home/jungleliu/.cache/bazel/_bazel_jungleliu/748f7d17089974aa1a9125aeba4ea413/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
		fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java in /home/jungleliu/.cache/bazel/_bazel_jungleliu/install/ee8d7e4b6774884ed2cd0aece6fc9fda/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify embedded Java (e.g. --javabase=@bazel_tools//tools/jdk:remote_jdk11)

**Comment by dpoluyanov** [comment]
It is a bazel thing, not related to bazel-wsl.
You should install `java` into your WSL distro (e.g. through `apt update && apt install -y openjdk-11-jdk` or add `build --javabase=@bazel_tools//tools/jdk:remote_jdk11` into your `.bazelrc` file.
I'd recommend to install all required packages from https://docs.bazel.build/versions/main/install-ubuntu.html#step-1-install-required-packages

**Comment by Jungle666** [comment]
Thanks.  add build --javabase=@bazel_tools//tools/jdk:remote_jdk11 into .bazelrc file. resove my problem.
